language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t darshansbg-react-image -f Dockerfile.dev .

script:
        - docker run darshansbg-react-image  npm run test -- --coverage
