language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t darshansbg-react -f Dockerfile.dev .

script:
        - docker run darshansbg-react npm run test -- --coverage
